### PR TITLE
Fix #339: Add RSpec test suite with SimpleCov for all Ruby scripts

### LINKED ISSUE #339: [TEST-001] Create test suite for critical scripts
## Summary

Zero test coverage across all 8 main scripts. The CI job named "Ruby Unit Tests" only runs smoke tests (help flags, syntax checks) rather than actual unit tests.

## Finding Details

- **Severity:** 🔴 Critical
- **Category:** Testing > Coverage
- **Effort:** XL (>3 days)

## Current State

- **Coverage:** 0/8 scripts tested (0%)
- **Untested conditional statements:** 79 across critical scripts
- **Scripts without tests:**
  - deploy.rb (496 lines, 61 conditionals)
  - cycle-keys.rb (170 lines, 8 conditionals)
  - encrypt-logs.rb (101 lines, 10 conditionals)
  - sync-jira-release
  - linters
  - ssm-jump
  - ssh-jump
  - generate-codeowners
  - brew-resources.rb

## Impact

- AWS infrastructure operations have no test coverage
- Regression bugs cannot be caught automatically
- Refactoring is risky without tests to verify behavior

## Recommended Fix

1. Create RSpec test suite for critical scripts (deploy.rb, cycle-keys.rb)
2. Add mocked AWS API integration tests using `aws-sdk-ruby` stubs
3. Configure SimpleCov for coverage reporting in CI
4. Set minimum coverage threshold (e.g., 70%)

## Example Test Structure

```ruby
# spec/deploy_spec.rb
require 'spec_helper'
require_relative '../deploy'

RSpec.describe 'deploy.rb' do
  let(:ec2_client) { Aws::EC2::Client.new(stub_responses: true) }
  
  describe 'wait_for_healthy_instances' do
    it 'waits until all targets are healthy' do
      # test implementation
    end
  end
end
```

---

*Generated from code review finding TEST-001*

### PR DESCRIPTION
**Pull request by ydesgagn**
## Summary

Add a comprehensive RSpec test suite with SimpleCov code coverage for all 4 Ruby scripts, replacing the previous smoke-command-only CI step. This closes #339.

**Key changes:**
- Add `rspec` and `simplecov` gems to `Gemfile` development group
- Create `.rspec` configuration and `spec/spec_helper.rb` with 80% minimum line+branch coverage
- Extract testable helper methods from `cycle-keys.rb` (3 methods), `encrypt-logs.rb` (2 methods), and `brew-resources.rb` (1 method)
- Add `if __FILE__ == $PROGRAM_NAME` guard clauses to all 4 scripts so they can be safely required
- Create `spec/deploy_spec.rb` (56 tests), `spec/cycle_keys_spec.rb` (11 tests), `spec/encrypt_logs_spec.rb` (10 tests), `spec/brew_resources_spec.rb` (7 tests) — 86 tests total
- Update `.rubocop.yml` with RSpec cop relaxations
- Update `.github/workflows/build.yml` to run `bundle exec rspec` instead of smoke commands

## Types of changes

- [ ] Bugfix (fixes an issue)
- [x] New feature (adds functionality)
- [x] Refactoring (improves code without changing functionality)
- [ ] Breaking change (incompatible changes)
- [ ] Build or security update (updates dependencies, libraries, or security patches)
- [ ] Code style or documentation update (formatting, renaming, or documentation changes)
- [ ] Other (please describe):

## Checklist

- [x] Unit tests added to validate my fix/feature
- [x] I have manually tested my change
- [ ] I did not add automation test. Why ?:
- [ ] Database changes requiring migration with downtime or reprocessing of existing data
- [ ] The SOUP file lists the risk Level, requirements and verification reasoning associated with each library
- [ ] `readme.md` includes sections on introduction, installation, usage, and contributing
- [ ] `docs/architecture.md` includes sections on the architecture diagram, software units, software of unknown provenance, critical algorithms and risk controls related to PII and security
- [ ] Impact on PII, privacy regulations (CCPA/GDPR/PIPEDA), CIS benchmarks or security (availability/confidentiality/integrity); management must be notified

### CODE REVIEW

File: spec/brew_resources_spec.rb [hunk 1]
```diff
@@ -0,0 +1,119 @@
+# frozen_string_literal: true
+
+RSpec.describe('brew-resources.rb') do
```
Comment (ydesgagn) [inline spec/brew_resources_spec.rb]: 📝 **[rubocop]** <RSpec/DescribeClass> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>The first argument to describe should be the class or module being tested.

File: spec/brew_resources_spec.rb [hunk 2]
```diff
@@ -0,0 +1,119 @@
...
+        expect(lines).to(include("        url 'https://rubygems.org/gems/nokogiri-1.15.2-arm64-darwin.gem'"))
+        expect(lines).to(include("        sha256 'xyz789'"))
+        expect(lines).to(include('      end'))
+        expect(lines).to(include('    end'))
+        expect(lines).to(include('  end'))
+      end
+    end
+
+    context 'with darwin x86_64 platform' do
+      let(:platform) { double('platform', os: 'darwin', cpu: 'x86_64') }
```
Comment (ydesgagn) [inline spec/brew_resources_spec.rb]: 📝 **[rubocop]** <RSpec/VerifiedDoubles> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Prefer using verifying doubles over normal doubles.

File: spec/brew_resources_spec.rb [hunk 3]
```diff
@@ -0,0 +1,119 @@
...
+      let(:spec) do
+        double(
+          'spec',
+          name: 'nokogiri',
+          full_name: 'nokogiri-1.15.2-x86_64-darwin',
+          platform: platform
+        )
```
Comment (ydesgagn) [inline spec/brew_resources_spec.rb]: 📝 **[rubocop]** <RSpec/VerifiedDoubles> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Prefer using verifying doubles over normal doubles.

File: spec/brew_resources_spec.rb [hunk 4]
```diff
@@ -0,0 +1,119 @@
...
+      end
+      let(:sha256) { 'intel123' }
+
+      it 'wraps in on_macos and on_intel blocks' do
```
Comment (ydesgagn) [inline spec/brew_resources_spec.rb]: 📝 **[rubocop]** <RSpec/MultipleExpectations> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Example has too many expectations [3/1].

File: spec/brew_resources_spec.rb [hunk 5]
```diff
@@ -0,0 +1,119 @@
...
+        lines = format_resource(spec, sha256)
+        expect(lines).to(include('  on_macos do'))
+        expect(lines).to(include('    on_intel do'))
+        expect(lines).to(include("      resource 'nokogiri' do"))
+      end
+    end
+
+    context 'with linux platform' do
+      let(:platform) { double('platform', os: 'linux', cpu: 'x86_64') }
```
Comment (ydesgagn) [inline spec/brew_resources_spec.rb]: 📝 **[rubocop]** <RSpec/VerifiedDoubles> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Prefer using verifying doubles over normal doubles.

File: spec/brew_resources_spec.rb [hunk 6]
```diff
@@ -0,0 +1,119 @@
...
+      let(:spec) do
+        double(
+          'spec',
+          name: 'nokogiri',
+          full_name: 'nokogiri-1.15.2-x86_64-linux',
+          platform: platform
+        )
```
Comment (ydesgagn) [inline spec/brew_resources_spec.rb]: 📝 **[rubocop]** <RSpec/VerifiedDoubles> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Prefer using verifying doubles over normal doubles.

File: spec/brew_resources_spec.rb [hunk 7]
```diff
@@ -0,0 +1,119 @@
...
+
+      it 'wraps in on_linux and on_intel blocks' do
+        lines = format_resource(spec, sha256)
+        expect(lines).to(include('  on_linux do'))
+        expect(lines).to(include('    on_intel do'))
+      end
+    end
+
+    context 'with linux arm64 platform' do
+      let(:platform) { double('platform', os: 'linux', cpu: 'aarch64') }
```
Comment (ydesgagn) [inline spec/brew_resources_spec.rb]: 📝 **[rubocop]** <RSpec/VerifiedDoubles> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Prefer using verifying doubles over normal doubles.

File: spec/brew_resources_spec.rb [hunk 8]
```diff
@@ -0,0 +1,119 @@
...
+      let(:spec) do
+        double(
+          'spec',
+          name: 'nokogiri',
+          full_name: 'nokogiri-1.15.2-aarch64-linux',
+          platform: platform
+        )
```
Comment (ydesgagn) [inline spec/brew_resources_spec.rb]: 📝 **[rubocop]** <RSpec/VerifiedDoubles> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Prefer using verifying doubles over normal doubles.

File: spec/brew_resources_spec.rb [hunk 9]
```diff
@@ -0,0 +1,119 @@
...
+      end
+      let(:sha256) { 'linuxarm123' }
+
+      it 'wraps in on_linux and on_arm blocks' do
```
Comment (ydesgagn) [inline spec/brew_resources_spec.rb]: 📝 **[rubocop]** <RSpec/MultipleExpectations> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Example has too many expectations [2/1].

File: spec/cycle_keys_spec.rb [hunk 10]
```diff
@@ -0,0 +1,132 @@
+# frozen_string_literal: true
+
+RSpec.describe('cycle-keys.rb') do
```
Comment (ydesgagn) [inline spec/cycle_keys_spec.rb]: 📝 **[rubocop]** <RSpec/DescribeClass> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>The first argument to describe should be the class or module being tested.

File: spec/cycle_keys_spec.rb [hunk 11]
```diff
@@ -0,0 +1,132 @@
...
+
+    it 'disables and deletes active secondary keys' do
+      metadata = [
+        double('key', access_key_id: primary_key_id, user_name: 'testuser', status: 'Active'),
+        double('key', access_key_id: 'AKIAI44QH8DHBSECONDARY', user_name: 'testuser', status: 'Active')
+      ]
+      cleanup_secondary_keys(iam, primary_key_id, metadata)
+      expect(iam).to(have_received(:update_access_key).with(hash_including(access_key_id: 'AKIAI44QH8DHBSECONDARY', status: 'Inactive')))
+      expect(iam).to(have_received(:delete_access_key).with(hash_including(access_key_id: 'AKIAI44QH8DHBSECONDARY')))
+    end
```
Comment (ydesgagn) [inline spec/cycle_keys_spec.rb]: 📝 **[rubocop]** <RSpec/ExampleLength> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Example has too many lines. [7/5]

File: spec/cycle_keys_spec.rb [hunk 12]
```diff
@@ -0,0 +1,132 @@
...
+  describe '#cleanup_secondary_keys' do
+    let(:iam)            { Aws::IAM::Client.new(stub_responses: true) }
+    let(:primary_key_id) { 'AKIAIOSFODNN7EXAMPLE'                     }
+
+    before do
+      allow(iam).to(receive(:update_access_key).and_call_original)
+      allow(iam).to(receive(:delete_access_key).and_call_original)
+    end
+
+    it 'disables and deletes active secondary keys' do
```
Comment (ydesgagn) [inline spec/cycle_keys_spec.rb]: 📝 **[rubocop]** <RSpec/MultipleExpectations> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Example has too many expectations [2/1].

File: spec/cycle_keys_spec.rb [hunk 13]
```diff
@@ -0,0 +1,132 @@
...
+        double('key', access_key_id: 'AKIAI44QH8DHBSECONDARY', user_name: 'testuser', status: 'Inactive')
+      ]
+      cleanup_secondary_keys(iam, primary_key_id, metadata)
+      expect(iam).not_to(have_received(:update_access_key))
+      expect(iam).to(have_received(:delete_access_key).with(hash_including(access_key_id: 'AKIAI44QH8DHBSECONDARY')))
+    end
+
+    it 'skips the primary key' do
+      metadata = [
+        double('key', access_key_id: primary_key_id, user_name: 'testuser', status: 'Active')
```
Comment (ydesgagn) [inline spec/cycle_keys_spec.rb]: 📝 **[rubocop]** <RSpec/VerifiedDoubles> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Prefer using verifying doubles over normal doubles.
